/**
 * Seed loader (S3) — pushes the S2 artifacts to the XTrace pool scope and the
 * relay, ahead of a demo (design v0.8 §11: induction operates over the pool,
 * so seed HOURS ahead — the closing message names when induction will be warm).
 *
 * Re-running is safe, but NOT because of upserts: XTrace ingest has none, so a
 * second run creates duplicate pool records. They carry the same `read_id`,
 * and K6's dedup is what keeps the census stable — do not attempt upsert
 * against an API that does not offer it. A detected re-run prints a warning.
 *
 * The relay is seeded FIRST (one bulk call): a pool write that then fails
 * leaves its relay entry in place, and M7's sweeper re-ingests from it — the
 * loader's failure report says exactly that.
 */

import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';

import type { PoolStore, Relay } from '../../src/contracts/modules.js';
import type { Read } from '../../src/contracts/types.js';
import type { Logger } from '../../src/config/logger.js';
import { parseRead } from '../../src/kernel/read.js';
import { placeNames } from '../../src/memory/readProse.js';
import { loadCorpus } from './validate-corpus.js';

export interface LoadSeedsDeps {
  pool: PoolStore;
  relay: Relay;
  logger: Logger;
  settleWindowSeconds: number;
  now: () => Date;
}

export interface LoadReport {
  total: number;
  relaySeeded: number;
  poolLoaded: number;
  /** read_ids whose POOL write failed — the relay copy remains, the sweeper recovers them. */
  failed: string[];
  rerunDetected: boolean;
  warmAt: string;
}

export function readSeedArtifact(path?: string): Read[] {
  // SL-14: `.pathname` URL-encodes spaces as `%20`, which is not a valid fs
  // path — `fileURLToPath` decodes it back to a real path on any checkout.
  const url = path ?? fileURLToPath(new URL('../../data/seeds/reads.json', import.meta.url));
  const raw = JSON.parse(readFileSync(url, 'utf8')) as { reads?: unknown[] };
  return (raw.reads ?? []).map((candidate) => parseRead(candidate));
}

/**
 * The demo pack (DEMO.2), read through the same parser as the base seed.
 *
 * It is a SEPARATE artifact rather than more rows in `data/seeds/reads.json` because that
 * file is PRNG-tuned so `pass neartie` provably holds, and appending to it re-rolls the
 * guarantee. Keeping them apart also keeps `pass census`'s manifest cross-check meaningful:
 * the manifest describes the base seed, and pack reads land as `over`, which the report
 * already discloses as "live reads joined" rather than flagging.
 *
 * Absence is not an error here — the pack is generated by `npm run demo:pack` and a checkout
 * that has never run it simply seeds the base corpus. Returning `[]` rather than throwing is
 * the difference between "you have no pack" and "seeding is broken".
 */
export function readPackArtifact(path?: string): Read[] {
  const url = path ?? fileURLToPath(new URL('../../data/demo/pack.json', import.meta.url));
  if (!existsSync(url)) return [];
  const raw = JSON.parse(readFileSync(url, 'utf8')) as { reads?: unknown[] };
  return (raw.reads ?? []).map((candidate) => parseRead(candidate));
}

export async function loadSeeds(reads: Read[], deps: LoadSeedsDeps): Promise<LoadReport> {
  const seedIds = new Set(reads.map((read) => read.read_id));
  const existing = await deps.relay.list();
  const rerunDetected = existing.some((entry) => seedIds.has(entry.read.read_id));
  if (rerunDetected) {
    deps.logger.line(
      'load-seeds: re-run detected (seed reads already on the relay) — pool duplicates will be created; K6 dedup keeps the census stable',
    );
  }

  const relaySeeded = await deps.relay.seed(reads);
  deps.logger.line(`load-seeds: relay seeded with ${relaySeeded} read(s)`);

  // ONE call per chunk of reads, not one per read (M12). The chunking and the grouping are
  // M2's policy, not this script's — the pool knows that a conversation is what an episode
  // spans and that reads sharing a driver belong in one. Sending 220 individual ingests, as
  // this used to, produced 220 episodes each paraphrasing a single read.
  const failed: string[] = [];
  let poolLoaded = 0;
  try {
    const handles = await deps.pool.writeReads(reads);
    poolLoaded = reads.length;
    deps.logger.line(
      `load-seeds: pool fed as ${handles.length} conversation(s) — episodes can span reads now`,
    );
  } catch (error) {
    // All-or-nothing on purpose: a partial batch would leave some drivers with a coherent
    // conversation and others with nothing, and the relay copy already holds every read, so
    // the sweeper's backfill is the recovery path (it re-ingests per read, which is worse
    // for induction but never loses data).
    failed.push(...reads.map((read) => read.read_id));
    deps.logger.line(
      `load-seeds: pool feed failed — all ${reads.length} read(s) are on the relay and countable; ` +
        `induction is degraded until a re-seed: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const warmAt = new Date(
    deps.now().getTime() + deps.settleWindowSeconds * 1000,
  ).toISOString();
  deps.logger.line(
    `load-seeds: done — ${poolLoaded}/${reads.length} pooled, ${failed.length} failed. ` +
      `Reads are countable NOW (the relay is the store, D-7). Only induction waits: ` +
      `settle window ${deps.settleWindowSeconds}s, warm no earlier than ${warmAt}. ` +
      `Seed hours ahead for a good induced claim, not to make the demo work.`,
  );
  return {
    total: reads.length,
    relaySeeded,
    poolLoaded,
    failed,
    rerunDetected,
    warmAt,
  };
}

async function main(): Promise<void> {
  const [{ loadConfig }, { createLogger }, clientModule, poolModule, relayModule] =
    await Promise.all([
      import('../../src/config/env.js'),
      import('../../src/config/logger.js'),
      import('../../src/memory/client.js'),
      import('../../src/memory/pool.js'),
      import('../../src/memory/relay.js'),
    ]);
  const config = loadConfig(); // throws naming any missing variable
  const logger = createLogger();
  const client = clientModule.createMemoryClient(
    clientModule.createFetchTransport({ baseUrl: config.xtraceBaseUrl, apiKey: config.xtraceApiKey }),
  );
  const report = await loadSeeds(readSeedArtifact(), {
    pool: poolModule.createPoolStore({ client, logger, placeName: placeNames(loadCorpus()) }),
    relay: relayModule.createRelayClient({ url: config.relayUrl, token: config.relayToken, logger }),
    logger,
    settleWindowSeconds: config.settleWindowSeconds,
    now: () => new Date(),
  });
  process.exit(report.failed.length === 0 ? 0 : 1);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  void main();
}
